---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
spec:
  project: services
  source:
    path: services/homeassistant
  destination:
    namespace: homeassistant
