---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Configure ufw to deny all incoming connections by default
  community.general.ufw:
    default: deny
    direction: incoming
  notify: Restart ufw service

- name: Allow ssh from ip range
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
    from: "192.168.1.0/24"
  notify: Restart ufw service

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart ssh service

- name: Ensure SSH protocol 2 is used
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Protocol'
    line: 'Protocol 2'
    state: present
  notify: Restart ssh service

- name: Disable password authentication for SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart ssh service

- name: Install automatic upgrades
  ansible.builtin.apt:
    name: unattended-upgrades,apt-listchanges
    state: present
