---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare

labels:
  - pairs:
      app.kubernetes.io/instance: cloudflared
      app.kubernetes.io/name: cloudflared
    includeSelectors: true
  - pairs:
      app.kubernetes.io/instance: cloudflared
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/part-of: cloudflare
      app.kubernetes.io/version: "1.1.0"
    includeTemplates: true

resources:
  - resources/deployment.yaml
  - resources/namespace.yaml
  - resources/sealed-secret.yaml
