apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: End user applications

  sourceRepos:
  - 'https://github.com/gsuquet/*'

  destinations:
  - namespace: '!kube-system'
    server: '*'
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Namespace resource whitelist - resources that can be deployed in the allowed namespaces
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
