apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform level infrastructure and tools

  sourceRepos:
  - https://bitnami-labs.github.io/sealed-secrets
  - https://charts.bitnami.com/bitnami
  - https://github.com/gsuquet/homelab.git

  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
