---
- name: Enable cgroup via boot commandline if not already enabled
  when: lookup('fileglob', '/boot/firmware/cmdline.txt', errors='warn') | length > 0
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ cgroup_item }}\b).*)$'
    replace: '\1 {{ cgroup_item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  loop_control:
    loop_var: cgroup_item
  notify: Reboot Pi

- name: Install Ubuntu Raspi Extra Packages
  ansible.builtin.apt:
    name: linux-modules-extra-raspi
    update_cache: true
    state: present
  when: "ansible_distribution_version is version('20.10', '>=') and ansible_distribution_version is version('24.04', '<')"
