---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
spec:
  encryptedData:
    TOKEN: AgAGEuqXzLgYN0QTIIQ2ePkA3bIisPRklLQeWduuXtZOnHTz6k7kcLgPiBabDQYkHDOdNxFKBq2NSwejeldAEY32AERqBmC+siCPTfIDgVtUWP03PUBSi57atLIvK/Tcj1VQJ7WoZguTZZKD2aITR7lEImEPl+tsOg1c81hwjyioIhqe9NMYHedRLkY/e35QIwdrH8EipUREqotmlTQgZtVJHmMAG+E/mo8Wc3NbABnwObKDKXWPBGYmbHA6zBxY6Pmi1T40VUVING3X/rhE5GIAe8N8AwiYAHWkVhnemuXX+dl7qHA9uKFbPr1MAYUdRkEEp8QilADTjBCKq5jpnkH/Z13ujr8sGjBcJpVdobIPx/fg9gnVcvKLb/w8XQuNYtG1r343XSjrAHWZ7YJ4iiDJMQspN1lNP17EMP+9EgouMdQo92DzvZPIaqV2ICShw/rJLiY6m+qBFT3O5KXxGMhFlIF9XuS6qgWXL2emn/9ldb/9tloWP64Hfv5WUZIIqOenBzLrgGZDPUC6D8micMgrQbMkK2s7rN22wrGXmoMxDO/dLe443F7GYrTD1KMj1BZXc0N/hdLFZFoyFv+JIHCjffE2JaEUDXwlVj2kxkE5PUStJ/EW4pqQh8Pt72BtWcqJeJF5iajiNxPOtbom2pTzYTp8ozsNP+6/ji8Pm3IoyFxF3VDHVhKeOK0tv2vuFULQSWYWOGzPdppfeh5LS7DNdADMFjvRixc2FBIss3+G5f/fm9EqpdQSAX735/zIr+Xxp0GEE8vmvtjwF+LyXF3ld8mpyIXaPSSV0hR360WozhLmgmCuO2inLJPkp+z0iVmqPIzmpbAKCvj8S2tSXR6pLelIGLcf+oxhMcIDv6LFMF4m6dQ+pFVUETQRC9CVzI/d7egVunRs1xK+ZN9vExA5JqE6/V+4+RnDsxUou5yVUBclMyn64vTu
  template:
    metadata:
      name: cloudflared-credentials
    type: Opaque
