apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: homeassistant
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "2026.3.4" # renovate: datasource=github-tags packageName=home-assistant/core
  name: homeassistant-cm-environment
  namespace: homeassistant
data:
  TZ: Europe/Paris
