---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zigbee2mqtt-secrets
spec:
  encryptedData:
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: AgCQ51+f3gsJW8sVXeVBEyuaioK8okhMI+UnQT1U550+dvvCqyqKt/BsJDjccO2+32dcUaicOXR41zcDJ5D98/Y2YdGZ9+yvrXjsghlxLYIpdhztCznNUlh/G1nufQxEUfCHcWLp2hyXZ1DODZlHOawG17mDEZX4Kn7BKqAplpsRp4+HaHI5LGFxHTyjCC2fVi/x9osSmkeJUvv1Zsy/R6b5E9n/vqhQydXNvqAO47l4Rz65pEKj6GelVRtIvh4s0SCZe5MyPXAMOUC1V0iDOZTOJlVYp5maBL7E1fOGLtXxGn20LJsftX/xtQCviFFp4X1agCnxDzXfBe4BQWwSyuvqbbb6z8I+ADW469YH0f5kXy0Jf+CoAE318SYCkmOEcGJeYVDkV+5RbySJyvYH6+atDMmnvMKrT4NHp1b5Xo6LWFUXRaQXSKdyCeouCiem06kLMjfDS0nAVii16rfUVel4GAb4FEhy6SFIcJ/8Nm3Hebd5W4F78ZmbiPZvIPYwhZ8kZI7EB+HGMhfSVl89gXC9dnpCmCc+yC1FcKS+POfcwfhTiThNwA6OpbttDDu6ROODM2buEXsUf/fBDRq1mGbu7oUwxbgHFRshPNHxDca5fXwQxfaT37mreznjtXcC0vDElo7igWbWtf6Ue1KwqBlm2Il2fbPUrHzZQVGGEai0TjFWw6oROSJ6tOWqmeLktedFakRDn56cC7YUVZkFLNBWnIF4NUzvR3iqGohTJFM=
  template:
    metadata:
      name: zigbee2mqtt-secrets
    type: Opaque
