all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  children:
    homepies:
      hosts:
        homepi01.local:
          ansible_user: homepi
          ansible_port: 22
    homepie_master:
      hosts:
        homepi01.local:
          ansible_user: homepi
          ansible_port: 22
