---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Set UFW default policies
  ufw:
    default: deny
    direction: incoming
  notify: Restart UFW service

- name: Allow SSH from ip range
  ufw:
    rule: allow
    port: 22
    proto: tcp
    from: "{{ firewall_ssh_allowed_incoming_ip }}"
  notify: Restart UFW service

- name: Allow HTTP and HTTPS from ip range
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    from: "{{ firewall_http_allowed_incoming_ip }}"
  with_items:
    - 80
    - 443
  notify: Restart UFW service

- name: Allow TCP 6443 10250 from ip range
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    from: "{{ firewall_k8s_allowed_incoming_ip }}"
  with_items:
    - 6443
    - 10250
  notify: Restart UFW service

- name: Enable UFW
  ufw:
    state: enabled
