---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.22@sha256:d219d3a72847f3aed6a1d66975972d3b17f86e39e8f6f6b86b4088b879c1a2d6
          ports:
            - containerPort: 8883
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/config/
              name: config
            - mountPath: /mosquitto/data/
              name: data
            - mountPath: /mosquitto/passwords/
              name: passwords
      volumes:
        - name: config
          configMap:
            name: mosquitto-cm-config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
        - name: passwords
          configMap:
            name: mosquitto-cm-passwords
