---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

labels:
  - pairs:
      app.kubernetes.io/instance: homepage
      app.kubernetes.io/name: homepage
    includeSelectors: true
  - pairs:
      app.kubernetes.io/instance: homepage
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: homepage
      app.kubernetes.io/part-of: homepage
      app.kubernetes.io/version: "1.5.0" # renovate: datasource=docker depName=ghcr.io/gethomepage/homepage
    includeTemplates: true

resources:
  - resources/deployment.yaml
  - resources/role.yaml
  - resources/sa.yaml
  - resources/secret.yaml
  - resources/service.yaml

configMapGenerator:
  - name: homepage-cm-config
    files:
      - configs/bookmarks.yaml
      - configs/custom.css
      - configs/custom.js
      - configs/docker.yaml
      - configs/kubernetes.yaml
      - configs/services.yaml
      - configs/settings.yaml
      - configs/widgets.yaml
