---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch.yaml
    target:
      kind: Application
  - target:
      kind: Application
      name: application-name
    patch: |-
      - op: replace
        path: /metadata/name
        value: grafana
