apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  project: network
  source:
    repoURL: 'https://github.com/gsuquet/homelab.git'
    targetRevision: HEAD
    path: services/ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
