---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-cm-config
  namespace: homeassistant
  labels:
    app.kubernetes.io/instance: homeassistant
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "1.0.2"
data:
  configuration.yaml: |
    default_config:

    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-cm-environment
  namespace: homeassistant
  labels:
    app.kubernetes.io/instance: homeassistant
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "1.0.2"
data:
  TZ: "Europe/Paris"
