---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app.kubernetes.io/instance: homeassistant
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: homeassistant
      app.kubernetes.io/name: homeassistant
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: homeassistant
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: homeassistant
        app.kubernetes.io/part-of: homeassistant
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:2025.5.3@sha256:8a99004ff832dbd535e6ac4d141042bc31141ff6a86b4d5bb288b3680fbceac1
        ports:
        - containerPort: 8123
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: config
        - mountPath: /etc/localtime/
          name: time
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-pvc-config
      - name: time
        persistentVolumeClaim:
          claimName: homeassistant-pvc-time
          readOnly: true
