---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeassistant

labels:
  - pairs:
      app.kubernetes.io/instance: homeassistant
      app.kubernetes.io/name: homeassistant
    includeSelectors: true
  - pairs:
      app.kubernetes.io/instance: homeassistant
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: homeassistant
      app.kubernetes.io/part-of: homeassistant
      app.kubernetes.io/version: "1.3.0"
    includeTemplates: true

resources:
  - resources/deployment.yaml
  - resources/pvc.yaml
  - resources/service.yaml

configMapGenerator:
  - name: homeassistant-cm-config
    files:
      - configuration.yaml=configs/configuration.yaml
  - name: homeassistant-cm-environment
    literals:
      - TZ=Europe/Paris
