---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: homeassistant
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/part-of: homeassistant
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.21@sha256:94f5a3d7deafa59fa3440d227ddad558f59d293c612138de841eec61bfa4d353
        ports:
        - containerPort: 8883
          protocol: TCP
        - containerPort: 9001
          protocol: TCP
        volumeMounts:
        - mountPath: /mosquitto/config/
          name: config
        - mountPath: /mosquitto/data/
          name: data
        - mountPath: /mosquitto/passwords/
          name: passwords
      volumes:
      - name: config
        configMap:
          name: mosquitto-cm
      - name: data
        persistentVolumeClaim:
          claimName: mosquitto-data
      - name: passwords
        secret:
          secretName: mosquitto-passwords
