---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant

labels:
  - pairs:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
    includeSelectors: true
  - pairs:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/part-of: mosquitto
      app.kubernetes.io/version: "2.0.22" # renovate: datasource=docker depName=eclipse-mosquitto
    includeTemplates: true

resources:
  - resources/deployment.yaml
  - resources/pvc.yaml
  - resources/service.yaml

configMapGenerator:
  - name: mosquitto-cm-config
    files:
      - mosquitto.conf=configs/mosquitto.conf
  - name: mosquitto-cm-passwords
    files:
      - passwords.txt=configs/passwords.txt
