---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: homeassistant
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "1.0.0"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
