apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: homeassistant
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
  - name: mqtt
    port: 8883
    targetPort: 8883
    protocol: TCP
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
