[env]
ANSIBLE_VERSION = "11.4.0" # renovate: datasource=pypi depName=ansible
ANSIBLE_CREATOR_VERSION = "25.3.1" # renovate: datasource=pypi depName=ansible-creator

[settings]
lockfile = true

[tools]
cilium-cli = '0.19.5'
cilium-hubble = '1.19.4'
git-cliff = '2.8.0'
github-cli = '2.98.0'
gitleaks = '8.30.1'
helm = '4.2.4'
kyverno = '1.18.1'
pre-commit = '4.6.2'
python = '3.14.7'
terraform = '1.16.0'
terraform-docs = '0.24.0'
tflint = '0.64.0'
trivy = '0.74.0'
typos = '1.49.1'
yq = '4.53.6'
