version: "3"
networks:
  homelab:
    driver: bridge
    external: true
volumes:
  caddy_data: {}
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homelab
    environment:
      - CADDY_INGRESS_NETWORKS=homelab
