---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant

labels:
  - pairs:
      app.kubernetes.io/instance: zigbee2mqtt
      app.kubernetes.io/name: zigbee2mqtt
    includeSelectors: true
  - pairs:
      app.kubernetes.io/instance: zigbee2mqtt
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: zigbee2mqtt
      app.kubernetes.io/part-of: zigbee2mqtt
      app.kubernetes.io/version: "2.6.0" # renovate: datasource=docker depName=ghcr.io/koenkk/zigbee2mqtt
    includeTemplates: true

resources:
  - resources/deployment.yaml
  - resources/pvc.yaml
  - resources/sealed-secret.yaml
  - resources/service.yaml

configMapGenerator:
  - name: zigbee2mqtt-cm-environment
    literals:
      - TZ=Europe/Paris
      - ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL=15
      - ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER=20
      - ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_FRONTEND_PACKAGE=zigbee2mqtt-windfront
      - ZIGBEE2MQTT_CONFIG_FRONTEND_URL=http://zigbee2mqtt.homeassistant.svc.cluster.local:8080
      - ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC=homeassistant
      - ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC=homeassistant/status
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mosquitto.homeassistant.svc.cluster.local:8883
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=zigbee2mqtt
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=ember
      - ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE=115200
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=tcp://192.168.1.28:6638
