---
- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd

- name: Install ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    namespace: argocd
    state: present

- name: Wait for ArgoCD to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: argocd
    label_selectors:
      - app.kubernetes.io/name=argocd-server
    wait: yes
    wait_timeout: 300

- name: Update argocd-cmd-params-cm ConfigMap to set server.insecure= "true"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
        namespace: argocd
      data:
        server.insecure: "true"
  notify: Restart ArgoCD server deployment

- name: Create Project ArgoCD
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../../../../argocd/settings/project-argocd.yml') | from_yaml }}"

- name: Create Application ArgoCD Apps
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../../../../argocd/settings/application-argocd-apps.yml') | from_yaml }}"

- name: Create Application ArgoCD Projects
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '../../../../argocd/settings/application-argocd-projects.yml') | from_yaml }}"
