---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netalertx

labels:
  - pairs:
      app.kubernetes.io/instance: netalertx
      app.kubernetes.io/name: netalertx
    includeSelectors: true
  - pairs:
      app.kubernetes.io/instance: netalertx
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: netalertx
      app.kubernetes.io/part-of: netalertx
      app.kubernetes.io/version: "25.8.6" # renovate: datasource=docker depName=ghcr.io/jokob-sk/netalertx
    includeTemplates: true

resources:
  - resources/deployment.yaml
  - resources/pvc.yaml
  - resources/service.yaml

configMapGenerator:
  - name: netalertx-cm-environment
    literals:
      - PORT=20211
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - LOADED_PLUGINS=["ARPSCAN", "CUSTPROP", "DBCLNP", "MQTT", "NEWDEV", "NMAP", "NTFPRCS", "SETPWD", "SYNC", "UI"]
