---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-name # Will be replaced by kustomization
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project-name # Will be replaced by kustomization
  source:
    repoURL: https://github.com/gsuquet/homelab.git
    targetRevision: main
    path: path/to/application # Will be replaced by kustomization
  destination:
    server: https://kubernetes.default.svc
    namespace: application-namespace # Will be replaced by kustomization
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
