name: Pull Request Labeler
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    uses: gsuquet/workflows/.github/workflows/automation-labeler.yml@43c68523c48e8f1b57e7ef87303e26abcf1e6e1b # v1.2.6
