---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actualbudget

labels:
  - pairs:
      app.kubernetes.io/instance: actualbudget
      app.kubernetes.io/name: actualbudget
    includeSelectors: true
  - pairs:
      app.kubernetes.io/instance: actualbudget
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: actualbudget
      app.kubernetes.io/part-of: actualbudget
      app.kubernetes.io/version: "25.10.0" # renovate: datasource=docker depName=ghcr.io/actualbudget/actual
    includeTemplates: true

resources:
  - resources/deployment.yaml
  - resources/pvc.yaml
  - resources/service.yaml
